export const RESTAURANTS_MOCK_DATA = [
  {
    info: {
      id: '74796',
      name: 'Five Star Janta',
      cloudinaryImageId: 'avlujvfa7huclgj7e8z8',
      locality: 'Ballupur',
      areaName: 'Ballupur',
      costForTwo: '₹500 for two',
      cuisines: ['Sweets', 'Bakery', 'Chinese', 'South Indian', 'North Indian'],
      avgRating: 4.4,
      parentId: '15743',
      avgRatingString: '4.4',
      totalRatingsString: '10K+',
      sla: {
        deliveryTime: 34,
        lastMileTravel: 5.7,
        serviceability: 'SERVICEABLE',
        slaString: '30-35 mins',
        lastMileTravelString: '5.7 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 22:40:00', opened: true },
      badges: {
        imageBadges: [
          {
            imageId: 'Rxawards/_CATEGORY-Mithai.png',
            description: 'Delivery!',
          },
          {
            imageId: 'v1695133679/badges/Pure_Veg111.png',
            description: 'pureveg',
          },
        ],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: 'Delivery!',
                  imageId: 'Rxawards/_CATEGORY-Mithai.png',
                },
              },
              {
                attributes: {
                  description: 'pureveg',
                  imageId: 'v1695133679/badges/Pure_Veg111.png',
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/five-star-janta-ballupur-dehradun-74796',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '411544',
      name: 'Drunken Monkey',
      cloudinaryImageId: 'ifntkwjevte75a60pc16',
      locality: 'General Mahadev Singh Road',
      areaName: 'Balliwala',
      costForTwo: '₹350 for two',
      cuisines: ['Beverages', 'Juices', 'Home Food'],
      avgRating: 4.5,
      parentId: '1729',
      avgRatingString: '4.5',
      totalRatingsString: '500+',
      sla: {
        deliveryTime: 31,
        lastMileTravel: 4.7,
        serviceability: 'SERVICEABLE',
        slaString: '30-35 mins',
        lastMileTravelString: '4.7 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 22:00:00', opened: true },
      badges: {
        imageBadges: [
          {
            imageId: 'v1695133679/badges/Pure_Veg111.png',
            description: 'pureveg',
          },
        ],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: 'pureveg',
                  imageId: 'v1695133679/badges/Pure_Veg111.png',
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/drunken-monkey-general-mahadev-singh-road-balliwala-dehradun-411544',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '685166',
      name: 'IGP Cakes',
      cloudinaryImageId: 'cc84d172c8acb034e61ffaeb2d2557e3',
      locality: 'GMS Road',
      areaName: 'Deh_Patel Nagar',
      costForTwo: '₹299 for two',
      cuisines: ['Desserts', 'Bakery'],
      avgRating: 4.6,
      veg: true,
      parentId: '392350',
      avgRatingString: '4.6',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 27,
        lastMileTravel: 2.4,
        serviceability: 'SERVICEABLE',
        slaString: '25-30 mins',
        lastMileTravelString: '2.4 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-23 00:00:00', opened: true },
      badges: {
        imageBadges: [
          {
            imageId: 'v1695133679/badges/Pure_Veg111.png',
            description: 'pureveg',
          },
        ],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: 'pureveg',
                  imageId: 'v1695133679/badges/Pure_Veg111.png',
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/igp-cakes-gms-road-deh-patel-nagar-dehradun-685166',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '69447',
      name: 'Gaylord Express',
      cloudinaryImageId: 'uj68ybtfwbydewraxzhm',
      locality: 'Paltan Bazar',
      areaName: 'Paltan Bazaar',
      costForTwo: '₹250 for two',
      cuisines: ['Bakery', 'Chinese', 'North Indian', 'Beverages'],
      avgRating: 3.8,
      parentId: '13696',
      avgRatingString: '3.8',
      totalRatingsString: '10K+',
      sla: {
        deliveryTime: 41,
        lastMileTravel: 6.7,
        serviceability: 'SERVICEABLE',
        slaString: '40-45 mins',
        lastMileTravelString: '6.7 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-29 00:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/gaylord-express-paltan-bazar-paltan-bazaar-dehradun-69447',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '415642',
      name: 'Murthal Paranthawala',
      cloudinaryImageId: 'deabin3rt4mbtcitgopv',
      locality: 'Haridwar Road',
      areaName: 'Race Course',
      costForTwo: '₹220 for two',
      cuisines: ['North Indian'],
      avgRating: 4.2,
      veg: true,
      parentId: '282923',
      avgRatingString: '4.2',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 42,
        lastMileTravel: 6.8,
        serviceability: 'SERVICEABLE',
        slaString: '40-45 mins',
        lastMileTravelString: '6.8 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-23 03:00:00', opened: true },
      badges: {
        imageBadges: [
          {
            imageId: 'v1695133679/badges/Pure_Veg111.png',
            description: 'pureveg',
          },
        ],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: 'pureveg',
                  imageId: 'v1695133679/badges/Pure_Veg111.png',
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: '₹100 OFF',
        subHeader: 'ABOVE ₹349',
        discountTag: 'FLAT DEAL',
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/murthal-paranthawala-haridwar-road-race-course-dehradun-415642',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '91350',
      name: 'Subway',
      cloudinaryImageId: '63178e3e64d503a479f2a2048a474552',
      locality: 'Chakrata Road',
      areaName: 'Ballupur',
      costForTwo: '₹350 for two',
      cuisines: ['Healthy Food', 'Salads', 'Snacks', 'Desserts', 'Beverages'],
      avgRating: 4.3,
      parentId: '2',
      avgRatingString: '4.3',
      totalRatingsString: '5K+',
      sla: {
        deliveryTime: 54,
        lastMileTravel: 6,
        serviceability: 'SERVICEABLE',
        slaString: '50-55 mins',
        lastMileTravelString: '6.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-23 01:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹150',
        discountTag: 'SAVE BIG',
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/subway-chakrata-road-ballupur-dehradun-91350',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '84229',
      name: 'Punjabi Dhaba',
      cloudinaryImageId: 'yyrjmyajqhyjq6mp1gha',
      locality: 'Paltan Bazar',
      areaName: 'Chukkuwala',
      costForTwo: '₹300 for two',
      cuisines: ['North Indian'],
      avgRating: 4.1,
      parentId: '1476',
      avgRatingString: '4.1',
      totalRatingsString: '10K+',
      sla: {
        deliveryTime: 37,
        lastMileTravel: 5.8,
        serviceability: 'SERVICEABLE',
        slaString: '35-40 mins',
        lastMileTravelString: '5.8 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 23:59:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/punjabi-dhaba-paltan-bazar-chukkuwala-dehradun-84229',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '571368',
      name: 'Crazy Moms Kitchen',
      cloudinaryImageId: 'ue6aqezwohtvwi3bq0sk',
      locality: 'Shakti Enclave',
      areaName: 'Balliwala',
      costForTwo: '₹200 for two',
      cuisines: ['North Indian', 'Fast Food', 'Desserts', 'Beverages'],
      avgRating: 4.7,
      parentId: '342993',
      avgRatingString: '4.7',
      totalRatingsString: '500+',
      sla: {
        deliveryTime: 55,
        lastMileTravel: 4.2,
        serviceability: 'SERVICEABLE',
        slaString: '55-60 mins',
        lastMileTravelString: '4.2 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 22:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/crazy-moms-kitchen-shakti-enclave-balliwala-dehradun-571368',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '606086',
      name: 'Vivan Home Kitchen',
      cloudinaryImageId: 'kko2kox537x8mr7go5mh',
      locality: 'Race Course',
      areaName: 'Chukkuwala',
      costForTwo: '₹300 for two',
      cuisines: ['Indian', 'Snacks'],
      avgRating: 4.8,
      veg: true,
      parentId: '360937',
      avgRatingString: '4.8',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 56,
        lastMileTravel: 6.6,
        serviceability: 'SERVICEABLE',
        slaString: '55-60 mins',
        lastMileTravelString: '6.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 23:59:00', opened: true },
      badges: {
        imageBadges: [
          {
            imageId: 'v1695133679/badges/Pure_Veg111.png',
            description: 'pureveg',
          },
        ],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: 'pureveg',
                  imageId: 'v1695133679/badges/Pure_Veg111.png',
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/vivan-home-kitchen-race-course-chukkuwala-dehradun-606086',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '319828',
      name: 'Bengali Fast Food (Home Kitchen)',
      cloudinaryImageId: 'nx3kfluagjt4pv8vr8av',
      locality: 'Kaulagarh Road',
      areaName: 'Kishan Nagar',
      costForTwo: '₹250 for two',
      cuisines: ['North Indian', 'Chinese', 'Bengali'],
      avgRating: 4.4,
      parentId: '43369',
      avgRatingString: '4.4',
      totalRatingsString: '500+',
      sla: {
        deliveryTime: 54,
        lastMileTravel: 7,
        serviceability: 'SERVICEABLE',
        slaString: '50-55 mins',
        lastMileTravelString: '7.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 14:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/bengali-fast-food-home-kitchen-kaulagarh-road-kishan-nagar-dehradun-319828',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '106489',
      name: 'Pahalwan Paratha Dhabba',
      cloudinaryImageId: 'dsvgh9ju3sqnphnfm9zy',
      locality: 'Prem Nagar',
      areaName: 'Prem Nagar',
      costForTwo: '₹300 for two',
      cuisines: ['North Indian', 'Chinese', 'Indian'],
      avgRating: 4,
      parentId: '15512',
      avgRatingString: '4.0',
      totalRatingsString: '10K+',
      sla: {
        deliveryTime: 45,
        lastMileTravel: 8.3,
        serviceability: 'SERVICEABLE',
        slaString: '40-45 mins',
        lastMileTravelString: '8.3 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-23 00:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '40% OFF', subHeader: 'UPTO ₹80' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/pahalwan-paratha-dhabba-prem-nagar-dehradun-106489',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '367799',
      name: 'Shree Gopalji Ki Hatti',
      cloudinaryImageId: '504930a5d8c91a7a2ccaa74f9bff3874',
      locality: 'Darshan Lal Chowk',
      areaName: 'Paltan Bazaar',
      costForTwo: '₹150 for two',
      cuisines: ['North Indian', 'Beverages'],
      avgRating: 4.4,
      veg: true,
      parentId: '184642',
      avgRatingString: '4.4',
      totalRatingsString: '500+',
      sla: {
        deliveryTime: 45,
        lastMileTravel: 6.6,
        serviceability: 'SERVICEABLE',
        slaString: '45-50 mins',
        lastMileTravelString: '6.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 20:05:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '15% OFF', subHeader: 'UPTO ₹100' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/shree-gopalji-ki-hatti-darshan-lal-chowk-paltan-bazaar-dehradun-367799',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '228222',
      name: 'Chetan Puri Delivery',
      cloudinaryImageId: 'ocydpqvgaqdcbrqzqc4p',
      locality: 'Hanuman Chowk',
      areaName: 'Paltan Bazaar',
      costForTwo: '₹350 for two',
      cuisines: ['North Indian'],
      avgRating: 4.4,
      veg: true,
      parentId: '452947',
      avgRatingString: '4.4',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 36,
        lastMileTravel: 5.7,
        serviceability: 'SERVICEABLE',
        slaString: '35-40 mins',
        lastMileTravelString: '5.7 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 16:00:00', opened: true },
      badges: {
        imageBadges: [
          {
            imageId: 'v1695133679/badges/Pure_Veg111.png',
            description: 'pureveg',
          },
        ],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: 'pureveg',
                  imageId: 'v1695133679/badges/Pure_Veg111.png',
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/chetan-puri-delivery-hanuman-chowk-paltan-bazaar-dehradun-228222',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '620538',
      name: 'The Eleganza',
      cloudinaryImageId: 'rkwr773sin35jo9njnm2',
      locality: 'Chakrata Road',
      areaName: 'Bengali Club',
      costForTwo: '₹350 for two',
      cuisines: ['Indian', 'Snacks'],
      avgRating: 4.3,
      parentId: '369708',
      avgRatingString: '4.3',
      totalRatingsString: '500+',
      sla: {
        deliveryTime: 62,
        lastMileTravel: 11.7,
        serviceability: 'SERVICEABLE',
        slaString: '60-65 mins',
        lastMileTravelString: '11.7 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 23:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/the-eleganza-chakrata-road-bengali-club-dehradun-620538',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '615956',
      name: 'Singh Darbar Sweets',
      cloudinaryImageId: 'pr8vq3b9bzijp3ovn3yo',
      locality: 'Kheri Gaon',
      areaName: 'Prem Nagar',
      costForTwo: '₹300 for two',
      cuisines: ['Sweets', 'Snacks', 'Chinese'],
      avgRating: 4.1,
      veg: true,
      parentId: '367272',
      avgRatingString: '4.1',
      totalRatingsString: '100+',
      sla: {
        deliveryTime: 41,
        lastMileTravel: 8.3,
        serviceability: 'SERVICEABLE',
        slaString: '40-45 mins',
        lastMileTravelString: '8.3 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 23:59:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/singh-darbar-sweets-kheri-gaon-prem-nagar-dehradun-615956',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '542447',
      name: 'Wellfed Foods',
      cloudinaryImageId: 'i2qzyeyfut60ioehrq12',
      locality: 'General Mahadev Singh Road',
      areaName: 'Ballupur',
      costForTwo: '₹200 for two',
      cuisines: ['Chinese', 'Snacks', 'Beverages'],
      avgRating: 4.2,
      veg: true,
      parentId: '326041',
      avgRatingString: '4.2',
      totalRatingsString: '500+',
      sla: {
        deliveryTime: 44,
        lastMileTravel: 4.2,
        serviceability: 'SERVICEABLE',
        slaString: '40-45 mins',
        lastMileTravelString: '4.2 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-23 04:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/wellfed-foods-general-mahadev-singh-road-ballupur-dehradun-542447',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '108973',
      name: 'Kalra Sweet Shop',
      cloudinaryImageId: '61fb153c4b74f61fac8473b634cc018a',
      locality: 'Tyagi Market',
      areaName: 'Prem Nagar',
      costForTwo: '₹350 for two',
      cuisines: ['Sweets', 'Snacks', 'Chinese', 'Beverages'],
      avgRating: 4,
      veg: true,
      parentId: '114130',
      avgRatingString: '4.0',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 38,
        lastMileTravel: 7.1,
        serviceability: 'SERVICEABLE',
        slaString: '35-40 mins',
        lastMileTravelString: '7.1 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 21:30:00', opened: true },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/kalra-sweet-shop-tyagi-market-prem-nagar-dehradun-108973',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '677672',
      name: 'Yellow Marigold House Cafe',
      cloudinaryImageId: 'cfbef7b8aba62f21fa7c728f0338108b',
      locality: 'Buddha Chowk',
      areaName: 'Race Course',
      costForTwo: '₹900 for two',
      cuisines: ['Continental', 'Asian', 'Thai', 'Beverages', 'Sushi'],
      avgRating: 4.5,
      parentId: '473401',
      avgRatingString: '4.5',
      totalRatingsString: '20+',
      sla: {
        deliveryTime: 50,
        lastMileTravel: 7.2,
        serviceability: 'SERVICEABLE',
        slaString: '50-55 mins',
        lastMileTravelString: '7.2 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 22:30:00', opened: true },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/yellow-marigold-house-cafe-buddha-chowk-race-course-dehradun-677672',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '314925',
      name: 'Melt - Hotel Saffron Leaf',
      cloudinaryImageId: 'kgwlvbxn3e8tmrojigrg',
      locality: 'General Mahadev Singh Road',
      areaName: 'Kaonli',
      costForTwo: '₹750 for two',
      cuisines: ['Indian', 'Continental', 'Chinese', 'Tandoor'],
      avgRating: 4.5,
      parentId: '135159',
      avgRatingString: '4.5',
      totalRatingsString: '100+',
      sla: {
        deliveryTime: 43,
        lastMileTravel: 2.6,
        serviceability: 'SERVICEABLE',
        slaString: '40-45 mins',
        lastMileTravelString: '2.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-29 00:00:00', opened: true },
      badges: {
        imageBadges: [{ imageId: 'newg.png', description: 'Gourmet' }],
      },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              { attributes: { description: 'Gourmet', imageId: 'newg.png' } },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: { header: '10% OFF', subHeader: 'UPTO ₹40' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/melt-hotel-saffron-leaf-general-mahadev-singh-road-kaonli-dehradun-314925',
      type: 'WEBLINK',
    },
  },
  {
    info: {
      id: '148051',
      name: 'Hotel Sunder Palace',
      cloudinaryImageId: 'adwbxvdijp7h7ct0spsk',
      locality: 'Sewla Kalan',
      areaName: 'Majra',
      costForTwo: '₹500 for two',
      cuisines: ['North Indian', 'Chinese'],
      avgRating: 4.3,
      parentId: '15322',
      avgRatingString: '4.3',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 32,
        lastMileTravel: 1.5,
        serviceability: 'SERVICEABLE',
        slaString: '30-35 mins',
        lastMileTravelString: '1.5 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2024-04-22 23:00:00', opened: true },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
      },
      aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: 'https://www.swiggy.com/restaurants/hotel-sunder-palace-sewla-kalan-majra-dehradun-148051',
      type: 'WEBLINK',
    },
  },
];
